[tool.mypy]
ignore_missing_imports = true
disallow_any_generics = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
namespace_packages = true
explicit_package_bases = true
exclude = ["thirdparty/"]

[tool.ruff]
extend-exclude = ["thirdparty"]
extend-include = ["SConstruct", "SCsub"]
line-length = 120
target-version = "py37"

[tool.ruff.lint]
extend-select = [
	"I", # isort
]
