name: Godot CI

on:
    pull_request:
    push:
      branches: [ master, 3.2, 3.1, 3.0 ]
jobs:
  windows-editor:
    runs-on: windows-2019
    name: Windows Editor
    env:
      SCONS_CACHE: ~/.scons_cache/
      SCONS_CACHE_LIMIT: 2048  
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with: 
        path: ~/scon_cache/
        key: ${{ runner.os }}-release_debug
    - name: Installation scons
      run: |
        python -m pip install scons pywin32

    - name: Compilation
      run: |
        scons -j6 warnings=all werror=yes platform=windows target=release_debug

  windows-release:
    runs-on: windows-2019
    name: Windows Release

    env:
     SCONS_CACHE: ~/.scons_cache/ 
     SCONS_CACHE_LIMIT: 2048
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with: 
        path: ~/scon_cache/
        key: ${{ runner.os }}-release
    - name: Installation scons
      run: |
        python -m pip install scons pywin32

    - name: Compilation
      run: |
        scons -j6 platform=windows tools=no warnings=all werror=yes target=release


