name: Godot CI

on:
  push:
    branches: [ master, 3.2, 3.1, 3.0, github_instead_travis ]
  pull_request:
    branches: [ master, 3.2, 3.1, 3.0, github_instead_travis ]

jobs:
  windows-editor:
    runs-on: windows-2019
    name: Windows Editor

    steps:
    - uses: actions/checkout@v2

    - name: Installation scons
      run: |
        python -m pip install scons

    - name: Compilation
      run: |
        scons -j6 platform=windows

  windows-release:
    runs-on: windows-2019
    name: Windows Release

    steps:
    - uses: actions/checkout@v2

    - name: Installation scons
      run: |
        python -m pip install scons

    - name: Compilation
      run: |
        scons -j6 platform=windows tools=no target=release


