name: Godot CI

on:
  push:
    branches: [ master, 3.2, 3.1, 3.0, github_instead_travis ]
  pull_request:
    branches: [ master, 3.2, 3.1, 3.0, github_instead_travis ]
jobs:
  windows-editor:
    runs-on: windows-2019
    name: Windows Editor
    env:
     SCONS_CACHE: ~/scons_cache/
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with: 
        path: ~/scon_cache/
        key: ${{ runner.os }}-wincache
    - name: Installation scons
      run: |
        python -m pip install scons pywin32

    - name: Compilation
      run: |
        scons -j6 werror=true warnings=all platform=windows

  windows-release:
    runs-on: windows-2019
    name: Windows Release

    env:
     SCONS_CACHE: ~/scons_cache/ 
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with: 
        path: ~/scon_cache/
        key: ${{ runner.os }}-wincache
    - name: Installation scons
      run: |
        python -m pip install scons pywin32

    - name: Compilation
      run: |
        scons -j6 platform=windows tools=no warnings=all werror=true target=release


